name: bosancica

networks:
  bosancica_network:
    external: true

services:
  bosancica-frontend:
    image: kulasinn/bosancica-ai:bosancica-frontend
    build: .
    container_name: bosancica-frontend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - bosancica_network
